{% set name = "google-cloud-error-reporting" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a818c7a758e5b6440a0aaee1dc52b2ecc072970d016d59e0e9a853bb43ef1c91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.0,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    - google-cloud-logging >=1.14.0,<4.0.0
    # most restrictive version so we can stay noarch: python
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.client
    - google.cloud.error_reporting
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-error-reporting
  summary: Google Cloud Error Reporting API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "The Stackdriver Error Reporting API counts, analyzes and aggregates the crashes in your running cloud services. A centralized error management interface displays the results with sorting and filtering capabilities. Opt-in to receive email and mobile alerts on new errors.\nSee the [quick start guide](https://googleapis.dev/python/clouderrorreporting/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/clouderrorreporting/latest/index.html
  dev_url: https://github.com/googleapis/python-error-reporting

extra:
  recipe-maintainers:
    - xylar
    - parthea
