{% set name = "google-cloud-error-reporting" %}
{% set version = "1.1.0" %}
{% set sha256 = "2fd6fe25343f7017c22e2733a0358c64b3171edc1669d0c8a1e1f07f86a048c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-cloud-logging >=1.14.0,<2.0.0dev

test:
  imports:
    - google.cloud.client
    - google.cloud.error_reporting

about:
  home: https://github.com/googleapis/python-error-reporting
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Stackdriver Error Reporting API client library
  description: "The Stackdriver Error Reporting API counts, analyzes and aggregates the crashes in your running cloud services. A centralized error management interface displays the results with sorting and filtering capabilities. Opt-in to receive email and mobile alerts on new errors.\nSee the [quick start guide](https://googleapis.dev/python/clouderrorreporting/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/clouderrorreporting/latest/index.html
  dev_url: https://github.com/googleapis/python-error-reporting

extra:
  recipe-maintainers:
    - parthea
